# 使用 Ubuntu 作为基础镜像
FROM ubuntu:latest

# 更新软件包列表并安装依赖
RUN apt-get update && \
    apt-get install -y curl gnupg2

# 添加 Node.js 源并安装 Node.js 和 Yarn
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

# 安装 Yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -y yarn

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 yarn.lock 文件到工作目录
COPY package.json ./

# 安装依赖
RUN yarn install --production

# 复制 .next 和 public 文件夹到工作目录
COPY .next .next
COPY public public

# 复制 ecosystem.config.js 文件到工作目录
COPY ecosystem.config.js ./

COPY next.config.js ./

# 安装 PM2 全局依赖
RUN yarn global add pm2

# 暴露端口
EXPOSE 3000

# 使用 PM2 运行 Next.js 应用程序
CMD ["pm2", "start", "ecosystem.config.js"]
