version: '3.8'

services:
  nextjs:
    image: multiple-app:latest  # 指定自定义镜像名称
    container_name: nextjs  # 指定自定义容器名称
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: pm2 yarn start
    volumes:
      - .:/app
    restart: always
